name: Feature request
description: Suggest an addition
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: The problem
      description: What are you trying to do that this package makes hard?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: What you have in mind
      description: An API sketch is welcome, but not required.
